all:
  exclude:
    - 'spec/**/*'
github:
  slug: Yegorov/tiny-blog
  access_token: ENV['PRONTO_GITHUB_ACCESS_TOKEN']
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 1500
verbose: true
