dist: xenial
language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - DB_USER=postgres
    - DB_PASS=''
bundler_args: --without production
before_install:
  - yarn install
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  # Use 9.6 auth config:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart
  - psql -c 'create database tiny_blog_test;' -U postgres
before_script:
  - bundle exec rails db:setup
script:
  - bundle exec rspec
